services:
  http:
    container_name: response-http
    build: .
    ports:
      - "80:8888"
    restart: unless-stopped

  https:
    container_name: response-https
    build: .
    ports:
      - "443:8443"
    environment:
      - PORT=8443
      - TLS_CERT_PATH=/cert/tls.crt
      - TLS_KEY_PATH=/cert/tls.key
    volumes:
      - ./temp_cert:/cert:ro
    restart: unless-stopped
